# Generated by Django 4.1.3 on 2022-12-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_song_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_searched_song',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_searched_song', to='api.song'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_searched_song',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_searched_song', to='api.song'),
        ),
    ]
