# Generated by Django 4.1.3 on 2022-12-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_current_searched_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=250),
        ),
    ]
