# Generated by Django 4.1.3 on 2022-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_artist_info',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
