# Generated by Django 4.1.3 on 2022-12-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlist',
            old_name='comment_list',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='song',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentlist',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.song'),
        ),
    ]
