# Generated by Django 4.1.3 on 2022-11-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchedsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchedSongs',
            new_name='SearchedSong',
        ),
    ]
